name: Fetch and Save Proxies

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  fetch-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Fetch and Save Proxies
        run: |
          # Ambil data dari ProxyScrape
          curl -s "https://api.proxyscrape.com/v4/free-proxy-list/get?request=display_proxies&proxy_format=protocolipport&format=text" > proxies.txt

          # Ambil data dari Geonode
          curl -s "https://proxylist.geonode.com/api/proxy-list?filterUpTime=90&limit=500&page=1&sort_by=lastChecked&sort_type=desc" | jq -r '.data[] | .protocols[] as $proto | "\($proto)://\(.ip):\(.port)"' >> proxies.txt

          # Ambil data dari 911Proxy
          curl -s "https://www.911proxy.com/detection/proxyList?limit=500&page=1&sort_by=lastChecked&sort_type=desc&filterUpTime=90" | jq -r '.data[] | .protocols[] as $proto | "\($proto)://\(.ip):\(.port)"' >> proxies.txt

          # Ambil data dari LumiProxy
          curl -s "https://api.lumiproxy.com/web_v1/free-proxy/list?page_size=500&page=1&uptime=90&language=en-us" | jq -r '.data.list[] | .protocol as $proto | if $proto == 8 then "socks5" elif $proto == 4 then "socks4" elif $proto == 2 then "https" else "http" end + "://\(.ip):\(.port)"' >> proxies.txt

          # Ambil data dari IPRoyal
          curl -s "http://43.135.31.113:8777/proxyList?limit=500&page=1&uptime=90&language=en-us" | jq -r '.data[] | .protocols[] as $proto | "\($proto)://\(.ip):\(.port)"' >> proxies.txt

          # Hapus duplikat
          sort -u proxies.txt -o proxies.txt

          # Pisahkan berdasarkan jenis
          grep '^http://' proxies.txt | sort -u > http.txt || true
          grep '^https://' proxies.txt | sort -u > https.txt || true
          grep '^socks4://' proxies.txt | sort -u > socks4.txt || true
          grep '^socks5://' proxies.txt | sort -u > socks5.txt || true
          cp proxies.txt all.txt

          # Pisahkan berdasarkan negara
          mkdir -p country
          while read line; do
            IP=$(echo "$line" | awk -F '://' '{print $2}' | awk -F ':' '{print $1}')
            COUNTRY=$(curl -s "https://ipinfo.io/$IP/country" || echo "UNKNOWN")
            echo "$line" >> "country/${COUNTRY}.txt"
          done < proxies.txt

      - name: Commit and Push with Random Emoji
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "trio666"
          git config --global user.email "github@triooo.co"
          EMOJIS=("🚀" "🔥" "🌟" "💡" "🔧" "✅" "📌" "📈" "🕵️" "💾")
          RANDOM_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]}
          git add http.txt https.txt socks4.txt socks5.txt all.txt country/
          git commit -m "Update proxy lists $RANDOM_EMOJI" || echo "No changes to commit"
          git push "https://x-access-token:${GH_PAT}@github.com/trio666/proxy-checker.git"
