name: Update Proxies

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false  # Không sử dụng credentials mặc định

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install
      working-directory: .github/workflows

    - name: Run app.js
      run: node app.js
      working-directory: .github/workflows

    - name: Move updated files to root directory
      run: |
        mv .github/workflows/all.txt .
        mv .github/workflows/http.txt .
        mv .github/workflows/https.txt .
        mv .github/workflows/socks4.txt .
        mv .github/workflows/socks5.txt .
        rsync -a .github/workflows/country/ country/
        rm -rf .github/workflows/country/*

    - name: Commit and Push with Random Emoji
      env:
        GH_PAT: ${{ secrets.GH_PAT }}  # Đảm bảo GH_PAT được lưu trong GitHub Secrets
      run: |
        git config --global user.name "neganok"
        git config --global user.email "hackersvn1@gmail.com"
        EMOJIS=("🛡️" "🔒" "🌐" "💻" "📡" "🔍" "🖥️" "📊" "📈" "🗂️" "🚀" "🔥")
        RANDOM_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]}
        TIMESTAMP=$(TZ=Asia/Jakarta date '+%H:%M %d/%m/%Y')
        git add all.txt http.txt https.txt socks4.txt socks5.txt country/
        git commit -m "Update proxy lists - $TIMESTAMP $RANDOM_EMOJI" || echo "No changes to commit"

        # Pull with token authentication
        git pull --rebase "https://x-access-token:${GH_PAT}@github.com/neganok/proxy-checker.git" main

        # Push with token authentication
        git push "https://x-access-token:${GH_PAT}@github.com/neganok/proxy-checker.git"
