name: Fetch and Save Proxies

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  fetch-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl parallel

      - name: Fetch and Save Proxies
        run: |
          mkdir -p proxies country
          temp_file=$(mktemp)

          fetch_proxies() {
            local url="$1"
            local jq_filter="$2"
            curl -s "$url" | jq -r "$jq_filter" | grep -E '^(http|https|socks4|socks5)://' >> "$temp_file" || true
          }

          export -f fetch_proxies

          parallel fetch_proxies ::: \
            "https://api.proxyscrape.com/v4/free-proxy-list/get?request=display_proxies&proxy_format=protocolipport&format=text" "cat" \
            "https://proxylist.geonode.com/api/proxy-list?filterUpTime=90&limit=500&page=1&sort_by=lastChecked&sort_type=desc" \
            ".data[] | .protocols[] as $proto | \"\($proto)://\(.ip):\(.port)\"" \
            "https://www.911proxy.com/detection/proxyList?limit=500&page=1&sort_by=lastChecked&sort_type=desc&filterUpTime=90" \
            ".data[] | .protocols[] as $proto | \"\($proto)://\(.ip):\(.port)\"" \
            "https://api.lumiproxy.com/web_v1/free-proxy/list?page_size=500&page=1&uptime=90&language=en-us" \
            ".data.list[] | \(.protocol | if . == 8 then \"socks5\" elif . == 4 then \"socks4\" elif . == 2 then \"https\" else \"http\" end) + \"://\(.ip):\(.port)\"" \
            "http://43.135.31.113:8777/proxyList?limit=500&page=1&uptime=90&language=en-us" \
            ".data[] | .protocols[] as $proto | \"\($proto)://\(.ip):\(.port)\""

          sort -u "$temp_file" -o proxies.txt
          rm "$temp_file"

          awk -F '://' '{print $2}' proxies.txt | awk -F ':' '{print $1}' | sort -u > unique_ips.txt
          parallel -j10 'IP={} && COUNTRY=$(curl -s "https://ipinfo.io/$IP/country" || echo "UNKNOWN") && echo "$IP" >> "country/${COUNTRY}.txt"' :::: unique_ips.txt
          rm unique_ips.txt

          grep '^http://' proxies.txt > http.txt || true
          grep '^https://' proxies.txt > https.txt || true
          grep '^socks4://' proxies.txt > socks4.txt || true
          grep '^socks5://' proxies.txt > socks5.txt || true
          cp proxies.txt all.txt

      - name: Commit and Push with Random Emoji
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "trio666"
          git config --global user.email "github@triooo.co"
          EMOJIS=("🚀" "🔥" "🌟" "💡" "🔧" "✅" "📌" "📈" "🕵️" "💾")
          RANDOM_EMOJI=${EMOJIS[$RANDOM % ${#EMOJIS[@]}]}
          git add http.txt https.txt socks4.txt socks5.txt all.txt country/
          git commit -m "Update proxy lists $RANDOM_EMOJI" || echo "No changes to commit"
          git push "https://x-access-token:${GH_PAT}@github.com/trio666/proxy-checker.git"
